#!/bin/bash
#SBATCH --partition=epyc-64
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --time=2:30:00
#SBATCH --mem=128GB
#SBATCH --account=fehder_718
#SBATCH --array=159-160 # job array index

module load gcc/8.3.0
module load python

export PYTHONPATH=/project/fehder_718/python/pkgs:${PYTHONPATH}

#echo "The SLURM ARRAY TASKID IS: $SLURM_ARRAY_TASK_ID"

python3 l2-1-subset-data.py $SLURM_ARRAY_TASK_ID
