#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=1:30:00
#SBATCH --mem=128GB
#SBATCH --account=fehder_718

module load gcc/8.3.0
module load python
module load stata

export PYTHONPATH=/project/fehder_718/python/pkgs:${PYTHONPATH}
export TMPDIR=/project/fehder_718/frt_2021b_data/


# run processing files
python3 1_proc_raw_data.py
python3 2_proc_year_impute.py
sbatch 3_process_regional.job